version: '3.7'

services:
  app:
    build:
      context: .
    privileged: true
    volumes:
      - type: volume
        source: akashita_mnesia
        target: /mnesia
      - type: volume
        source: akashita_tmp
        target: /akashita

volumes:
  akashita_mnesia:
  akashita_tmp:
