%
% Dynamic rebar configuration
%
% If a user_vm.args exists, use that instead of the default.
case file:read_file_info("config/user_vm.args") of
    {ok, _FileInfo} ->
        Relx = lists:keyfind(relx, 1, CONFIG),
        RelxNew = lists:keyreplace(vm_args, 1, Relx, {vm_args, "./config/user_vm.args"}),
        lists:keyreplace(relx, 1, CONFIG, RelxNew);
    {error, enoent} ->
        CONFIG
    % else, surface the error
end.
