version: '3.7'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    privileged: true
    volumes:
      - type: volume
        source: akashita_mnesia
        target: /mnesia
      - type: volume
        source: akashita_tmp
        target: /akashita
    stdin_open: true
    tty: true

volumes:
  akashita_mnesia:
  akashita_tmp:
