version: '3.7'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    privileged: true
    volumes:
      - type: volume
        source: mnesia_test
        target: /mnesia
    stdin_open: true
    tty: true

volumes:
  mnesia_test:
